### ISSUE TITLE
ENIGMA variants not shown to also be in ClinVar in the merged data

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-pipeline#157] opened 2016-05-12 02:32 UTC
All the ENIGMA variants are now also in ClinVar.  But the last time I ran variant-merging.py, roughly 20 ENIGMA variants seemed to be specific to ENIGMA (i.e. not in ClinVar).  Here is one example from ClinVarBrca.vcf in the pipeline_input directory.
17	43039999	.	-	AT	.	.	Origin=germline;Symbol=BRCA1;DateLastUpdated=2015-01-12;Method=curation;ClinicalSignificance=Benign;HGVS=NM_007294.3.c.*5678_*5679insAT;Submitter=Evidence-based_Network_for_the_Interpretation_of_Germline_Mutant_Alleles_(ENIGMA);Genomic_Coordinate=chr17.43039999.->AT;Protein=None;SCV=SCV000244502;ID=455998

**Comment by MollyZhang** [comment] 2016-06-29 00:43
[problematic_ENIGMA_variants_GRCh38.txt](https://github.com/BD2KGenomics/brca-pipeline/files/338326/problematic_ENIGMA_variants_GRCh38.txt)
there are 20 of such variants, all of them are insertion, with genomic coordinate like "chr17:43100574:->AT", attached is the detail of all such 20 variants.

**Comment by melissacline** [comment] 2016-06-29 01:47
Looking at one at random

NM_007294.3:c.*5678_*5679insAT  Evidence-based Network for the
Interpretation of Germline Mutant Alleles (ENIGMA)       Benign
2015-01-12      SCV000244502  455998  germline        curation
chr17:43039999:->AT     BRCA1   None

It looks like it made it into ClinVarBrca.vcf in the pipeline_input
subdirectory

17 43039999 . - AT . .
Origin=germline;Symbol=BRCA1;DateLastUpdated=2015-01-12;Method=curation;ClinicalSignificance=Benign;HGVS=NM_007294.3.c.*5678_*5679insAT;Submitter=Evidence-based_Network_for_the_Interpretation_of_Germline_Mutant_Alleles_(ENIGMA);Genomic_Coordinate=chr17.43039999.->AT;Protein=None;SCV=SCV000244502;ID=455998

So then, the question becomes: where did we lose it when we aggregated the
variants in that directory?

**Comment by MollyZhang** [comment] 2016-06-29 20:03
that's what I am working on now. I am combing through the variant merging script to find out where it got lost.

**Comment by MollyZhang** [comment] 2016-06-29 22:03
Okay, it turns out this particular variant "17 43039999 . - AT . .", it's deemed to have a "wrong genomic coordiante" based on string comparison and removed from variant merging, while the same variant is deemed to have a correct genomic cordinate in ENIGMA input, so that's likely where the problem is, and I am looking at that part of the code next.

**Comment by MollyZhang** [comment] 2016-06-30 19:48
fixed the bug of identifying a variant as having a wrong genomic coordinate when in fact it's not wrong. 
Now all the the 20 problematic variants are resolved, except for one:
chr17:43095105:->CCT
This variant is present in ClinVar as chr17:43095106:CCT>CCTCCT
They are the same variants, I am going to look into why they are not merged as one variant next.

**Comment by MollyZhang** [comment] 2016-06-30 23:00
Fixed the problem with the last variant, it's an issue in string comparison which doesn't deal with ref string being an empty string correctly.

**Closed** 2016-10-28 16:37 UTC
Labels: bug
